# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Stage 1: Build
FROM node:lts-alpine AS builder
WORKDIR /app

# Copy project files (including source) before install to allow prepare script to run
COPY package.json yarn.lock tsconfig.json ./
COPY src ./src

# Install dependencies and build
RUN yarn install --frozen-lockfile
RUN yarn build

# Stage 2: Runtime
FROM node:lts-alpine
WORKDIR /app

# Copy built files and production dependencies manifest
COPY --from=builder /app/build ./build
COPY package.json yarn.lock ./

# Install only production dependencies
RUN yarn install --production --frozen-lockfile

# Set environment
ENV NODE_ENV=production

# Default command to run the MCP server
CMD ["node", "build/index.js"]
